module character_token
  implicit none

  !> Character Tokens
  character(len=1), parameter :: LOWER_CASE_A = "a"
  character(len=1), parameter :: LOWER_CASE_B = "b"
  character(len=1), parameter :: LOWER_CASE_C = "c"
  character(len=1), parameter :: LOWER_CASE_D = "d"
  character(len=1), parameter :: LOWER_CASE_E = "e"
  character(len=1), parameter :: LOWER_CASE_F = "f"
  character(len=1), parameter :: LOWER_CASE_G = "g"
  character(len=1), parameter :: LOWER_CASE_H = "h"
  character(len=1), parameter :: LOWER_CASE_I = "i"
  character(len=1), parameter :: LOWER_CASE_J = "j"
  character(len=1), parameter :: LOWER_CASE_K = "k"
  character(len=1), parameter :: LOWER_CASE_L = "l"
  character(len=1), parameter :: LOWER_CASE_M = "m"
  character(len=1), parameter :: LOWER_CASE_N = "n"
  character(len=1), parameter :: LOWER_CASE_O = "o"
  character(len=1), parameter :: LOWER_CASE_P = "p"
  character(len=1), parameter :: LOWER_CASE_Q = "q"
  character(len=1), parameter :: LOWER_CASE_R = "r"
  character(len=1), parameter :: LOWER_CASE_S = "s"
  character(len=1), parameter :: LOWER_CASE_T = "t"
  character(len=1), parameter :: LOWER_CASE_U = "u"
  character(len=1), parameter :: LOWER_CASE_V = "v"
  character(len=1), parameter :: LOWER_CASE_W = "w"
  character(len=1), parameter :: LOWER_CASE_X = "x"
  character(len=1), parameter :: LOWER_CASE_Y = "y"
  character(len=1), parameter :: LOWER_CASE_Z = "z"
  character(len=1), parameter :: UPPER_CASE_A = "A"
  character(len=1), parameter :: UPPER_CASE_B = "B"
  character(len=1), parameter :: UPPER_CASE_C = "C"
  character(len=1), parameter :: UPPER_CASE_D = "D"
  character(len=1), parameter :: UPPER_CASE_E = "E"
  character(len=1), parameter :: UPPER_CASE_F = "F"
  character(len=1), parameter :: UPPER_CASE_G = "G"
  character(len=1), parameter :: UPPER_CASE_H = "H"
  character(len=1), parameter :: UPPER_CASE_I = "I"
  character(len=1), parameter :: UPPER_CASE_J = "J"
  character(len=1), parameter :: UPPER_CASE_K = "K"
  character(len=1), parameter :: UPPER_CASE_L = "L"
  character(len=1), parameter :: UPPER_CASE_M = "M"
  character(len=1), parameter :: UPPER_CASE_N = "N"
  character(len=1), parameter :: UPPER_CASE_O = "O"
  character(len=1), parameter :: UPPER_CASE_P = "P"
  character(len=1), parameter :: UPPER_CASE_Q = "Q"
  character(len=1), parameter :: UPPER_CASE_R = "R"
  character(len=1), parameter :: UPPER_CASE_S = "S"
  character(len=1), parameter :: UPPER_CASE_T = "T"
  character(len=1), parameter :: UPPER_CASE_U = "U"
  character(len=1), parameter :: UPPER_CASE_V = "V"
  character(len=1), parameter :: UPPER_CASE_W = "W"
  character(len=1), parameter :: UPPER_CASE_X = "X"
  character(len=1), parameter :: UPPER_CASE_Y = "Y"
  character(len=1), parameter :: UPPER_CASE_Z = "Z"

end module character_token

